@ECHO OFF

REM TROCA O DIRETORIO ATUAL PARA O POSTGRES PARA EVITAR PROBLEMAS...
cd "%~dp0\ServerBin\PostgreSQL\14\"

ECHO "TENTANDO PARAR O POSTGRESQL CASO ESTEJA RODANDO"
start cmd /c "StopDB.bat"
ECHO "TENTANDO INICIAR O POSTGRESQL"
start cmd /c "StartDB.bat"

REM TROCA O DIRETORIO ATUAL PARA O MQTT PARA EVITAR PROBLEMAS...
cd ..\..\MQTT

ECHO "TENTANDO PARAR O MQTT BROKER CASO ESTEJA RODANDO"
taskkill /IM "mosquitto.exe" /F
ECHO "TENTANDO INICIAR O MQTT BROKER"
start cmd /c "mosquitto.exe -v -p 1884"

ECHO "PRESSIONE QUALQUER TECLA PARA ENCERRAR O BANCO DE DADOS E O MQTT"
@pause
start cmd /c "%~dp0\ServerBin\PostgreSQL\14\StopDB.bat"
taskkill /IM "mosquitto.exe" /F
